package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/legendaryos/builder/src/config"
	"github.com/legendaryos/builder/src/ui"
)

// CloudBuilder builds an OCI bootc container image using podman.
//
// Pipeline:
//   1. Validate project
//   2. Prepare build/ dirs
//   3. Copy repos/ into build context
//   4. Generate Containerfile  (from config + packages/install.packages + files/ + scripts/)
//   5. podman build --tag <registry/image:tag>
//   6. (optional) podman push
//   7. (optional) cosign sign
type CloudBuilder struct {
	cfg     *config.Config
	paths   *config.Paths
	verbose bool
	release bool
}

func NewCloud(cfg *config.Config, paths *config.Paths, verbose, release bool) *CloudBuilder {
	return &CloudBuilder{cfg: cfg, paths: paths, verbose: verbose, release: release}
}

func (b *CloudBuilder) Validate() error {
	if b.cfg.Project.BaseDistro != "fedora" {
		return fmt.Errorf("unsupported distro %q — only 'fedora' is supported", b.cfg.Project.BaseDistro)
	}
	if b.cfg.Project.BaseVersion < 44 {
		return fmt.Errorf("Fedora %d is not supported — minimum is Fedora 44", b.cfg.Project.BaseVersion)
	}
	ui.OK("Project valid — Fedora %d / %s", b.cfg.Project.BaseVersion, b.cfg.Project.Arch)
	return nil
}

func (b *CloudBuilder) PrepareDirs() error {
	storageDir := b.paths.PodmanStorage
	dirs := []string{
		b.paths.BuildDir,
		b.paths.CacheDir,
		b.paths.OutputDir,
		filepath.Join(b.paths.BuildDir, "context", "repos"),
		filepath.Join(storageDir, "graph"),
		filepath.Join(storageDir, "run"),
		filepath.Join(storageDir, "tmp"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			return fmt.Errorf("cannot create %s: %w", d, err)
		}
	}

	// Write storage.conf immediately so login/pull can use it
	storageCfg := filepath.Join(b.paths.BuildDir, "storage.conf")
	content := fmt.Sprintf("[storage]\ndriver = \"overlay\"\ngraphRoot = \"%s/graph\"\nrunRoot = \"%s/run\"\n",
		storageDir, storageDir)
	if err := os.WriteFile(storageCfg, []byte(content), 0644); err != nil {
		return fmt.Errorf("cannot write storage.conf: %w", err)
	}

	ui.OK("Build directories ready")
	ui.Info("Podman storage: %s", storageDir)
	return nil
}

// CopyRepos copies *.repo files from repos/ into the build context so the
// Containerfile can reference them with a COPY instruction.
func (b *CloudBuilder) CopyRepos() error {
	if _, err := os.Stat(b.paths.ReposDir); os.IsNotExist(err) {
		ui.Info("No repos/ directory — using base image defaults")
		return nil
	}
	entries, err := os.ReadDir(b.paths.ReposDir)
	if err != nil {
		return fmt.Errorf("cannot read repos/: %w", err)
	}
	destDir := filepath.Join(b.paths.BuildDir, "context", "repos")
	count := 0
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".repo") {
			data, err := os.ReadFile(filepath.Join(b.paths.ReposDir, e.Name()))
			if err != nil {
				return err
			}
			if err := os.WriteFile(filepath.Join(destDir, e.Name()), data, 0644); err != nil {
				return err
			}
			ui.Info("Repo: %s", e.Name())
			count++
		}
	}
	ui.OK("Copied %d repo file(s) into build context", count)
	return nil
}

// GenerateContainerfile renders the Containerfile and writes it to build/Containerfile.
func (b *CloudBuilder) GenerateContainerfile(platform string) error {
	installPkgs, err := config.ReadPackageList(b.paths.InstallPkgs)
	if err != nil {
		return fmt.Errorf("cannot read install.packages: %w", err)
	}
	removePkgs, err := config.ReadPackageList(b.paths.RemovePkgs)
	if err != nil {
		return fmt.Errorf("cannot read remove.packages: %w", err)
	}

	cf := b.renderContainerfile(installPkgs, removePkgs, platform)

	cfPath := filepath.Join(b.paths.BuildDir, "Containerfile")
	if err := os.WriteFile(cfPath, []byte(cf), 0644); err != nil {
		return fmt.Errorf("cannot write Containerfile: %w", err)
	}
	ui.OK("Containerfile → %s", cfPath)

	if b.verbose {
		ui.Divider()
		fmt.Fprint(ui.Out, cf)
		ui.Divider()
	}
	if len(installPkgs) > 0 {
		ui.PackageListDisplay("Will install", installPkgs)
	}
	if len(removePkgs) > 0 {
		ui.PackageListDisplay("Will remove", removePkgs)
	}
	return nil
}

func (b *CloudBuilder) renderContainerfile(install, remove []string, platform string) string {
	cfg := b.cfg
	base := fmt.Sprintf("quay.io/fedora/fedora-bootc:%d", cfg.Project.BaseVersion)

	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}
	comment := func(s string) { line("# " + s) }
	blank := func() { line("") }

	comment("╔══════════════════════════════════════════════════════════════╗")
	comment("║  Generated by LegendaryOS Builder — DO NOT EDIT MANUALLY   ║")
	comment("║  Regenerate with: legendaryos build cloud                   ║")
	comment("╚══════════════════════════════════════════════════════════════╝")
	blank()

	// FROM
	line("FROM --platform=%s %s", platform, base)
	blank()

	// Labels
	comment("── Labels ───────────────────────────────────────────────────────")
	line("LABEL org.opencontainers.image.title=%q", cfg.Project.Name)
	line("LABEL org.opencontainers.image.version=%q", cfg.Project.Version)
	line("LABEL org.opencontainers.image.description=%q", cfg.Project.Description)
	line("LABEL org.opencontainers.image.licenses=%q", cfg.Project.License)
	line("LABEL com.legendaryos.builder.version=\"1.0.0\"")
	blank()

	// Custom repos
	if hasDir(b.paths.ReposDir) {
		comment("── Custom repositories ────────────────────────────────────────────")
		comment("  Copied from repos/ by legendaryos into build/context/repos/")
		line("COPY build/context/repos/ /etc/yum.repos.d/")
		blank()
	}

	// Local RPMs from packages/
	if hasDir(b.paths.PackagesDir) {
		comment("── Local RPM packages (packages/) ─────────────────────────────────")
		line("COPY packages/ /tmp/los-rpms/")
		line("RUN dnf install -y /tmp/los-rpms/*.rpm 2>/dev/null || true \\")
		line("    && rm -rf /tmp/los-rpms")
		blank()
	}

	// scripts/before/ — run BEFORE package install
	if hasDir(b.paths.ScriptsBefore) {
		comment("── scripts/before/ — run BEFORE package install ───────────────────")
		comment("  .sh → bash   .py → python3   .pl → perl   .rb → ruby")
		line("COPY scripts/before/ /tmp/los-scripts-before/")
		line("RUN set -eux \\")
		line("    && for f in $(ls /tmp/los-scripts-before/*.sh  2>/dev/null | sort); do bash    \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts-before/*.py  2>/dev/null | sort); do python3 \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts-before/*.pl  2>/dev/null | sort); do perl    \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts-before/*.rb  2>/dev/null | sort); do ruby    \"$f\"; done \\")
		line("    && rm -rf /tmp/los-scripts-before")
		blank()
	}

	// files/before/ overlay
	if hasDir(b.paths.FilesBefore) {
		comment("── Pre-install overlay (files/before/) ────────────────────────────")
		line("COPY files/before/ /")
		blank()
	}

	// Install packages
	if len(install) > 0 {
		comment("── Install packages (packages/install.packages) ───────────────────")
		line("RUN dnf install -y --skip-unavailable \\")
		for _, pkg := range install {
			line("    %s \\", pkg)
		}
		line("    && dnf clean all \\")
		line("    && rm -rf /var/cache/dnf")
		blank()
	}

	// Remove packages
	if len(remove) > 0 {
		comment("── Remove packages (packages/remove.packages) ─────────────────────")
		line("RUN dnf remove -y \\")
		for i, pkg := range remove {
			if i < len(remove)-1 {
				line("    %s \\", pkg)
			} else {
				line("    %s", pkg)
			}
		}
		blank()
	}

	// files/after/ overlay
	if hasDir(b.paths.FilesAfter) {
		comment("── Post-install overlay (files/after/) ────────────────────────────")
		line("COPY files/after/ /")
		blank()
	}

	// scripts/after/ — run AFTER package install
	if hasDir(b.paths.ScriptsAfter) {
		comment("── scripts/after/ — run AFTER package install ─────────────────────")
		comment("  .sh → bash   .py → python3   .pl → perl   .rb → ruby")
		line("COPY scripts/after/ /tmp/los-scripts-after/")
		line("RUN set -eux \\")
		line("    && for f in $(ls /tmp/los-scripts-after/*.sh  2>/dev/null | sort); do bash    \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts-after/*.py  2>/dev/null | sort); do python3 \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts-after/*.pl  2>/dev/null | sort); do perl    \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts-after/*.rb  2>/dev/null | sort); do ruby    \"$f\"; done \\")
		line("    && rm -rf /tmp/los-scripts-after")
		blank()
	}

	// System configuration
	comment("── System configuration ────────────────────────────────────────────")
	if cfg.System.Hostname != "" {
		line("RUN echo %q > /etc/hostname", cfg.System.Hostname)
	}
	if cfg.System.Locale != "" {
		line("RUN echo 'LANG=%s' > /etc/locale.conf", cfg.System.Locale)
	}
	if cfg.System.Keyboard != "" {
		line("RUN echo 'KEYMAP=%s' > /etc/vconsole.conf", cfg.System.Keyboard)
	}
	if cfg.System.Timezone != "" {
		line("RUN ln -sf /usr/share/zoneinfo/%s /etc/localtime || true", cfg.System.Timezone)
	}
	if cfg.System.SELinux != "" {
		line("RUN sed -i 's/^SELINUX=.*/SELINUX=%s/' /etc/selinux/config 2>/dev/null || true", cfg.System.SELinux)
	}
	for _, svc := range cfg.System.Services {
		line("RUN systemctl enable  %s 2>/dev/null || true", svc)
	}
	for _, svc := range cfg.System.Disable {
		line("RUN systemctl disable %s 2>/dev/null || true", svc)
	}
	if cfg.System.Firewall {
		line("RUN systemctl enable firewalld.service 2>/dev/null || true")
	}
	blank()

	// Release mode
	if b.release {
		comment("── Release: strip debug symbols ────────────────────────────────────")
		line("RUN dnf remove -y gdb-minimal 2>/dev/null || true \\")
		line("    && find /usr/lib/debug -type f -delete 2>/dev/null || true \\")
		line("    && find /usr/src/debug -type f -delete 2>/dev/null || true")
		blank()
	}

	// bootc commit — MUST be last
	comment("── bootc: commit ostree layer — MUST be the last RUN ───────────────")
	line("RUN ostree container commit")

	return sb.String()
}

// RegistryLogin logs into the OCI registry using podman login.
// Uses the isolated storage so credentials don't touch global podman config.
func (b *CloudBuilder) RegistryLogin(registry, username, token string) error {
	if token == "" {
		ui.Info("No token — skipping registry login")
		return nil
	}
	if username == "" {
		username = "token" // ghcr.io accepts any username with a PAT
	}
	ui.Info("Logging into %s as %s", registry, username)
	storageCfg := filepath.Join(b.paths.BuildDir, "storage.conf")
	env := append(os.Environ(), "CONTAINERS_STORAGE_CONF="+storageCfg)
	return b.runEnv(env, "podman", "login",
		"--username", username,
		"--password", token,
		registry,
	)
}


//
// Storage isolation:
//   All podman layers, images and tmp files are written to
//   build/podman-storage  (inside the project directory).
//   This means you can put the project on any disk with enough space
//   and podman will never touch /var/tmp or ~/.local/share/containers.
//
//   Implementation: we pass --storage-driver=overlay and set
//   CONTAINERS_STORAGE_CONF + XDG_DATA_HOME env vars so this instance
//   of podman uses a completely separate storage root without touching
//   the user's global podman configuration.
func (b *CloudBuilder) PodmanBuild(tag string, noCache bool) error {
	cfPath := filepath.Join(b.paths.BuildDir, "Containerfile")
	storageCfg := filepath.Join(b.paths.BuildDir, "storage.conf")

	args := []string{"build", "--tag", tag, "--file", cfPath}
	if noCache {
		args = append(args, "--no-cache")
	}
	if b.release {
		args = append(args, "--squash-all")
	}
	args = append(args, b.paths.Root)

	ui.Info("podman %s", strings.Join(args, " "))

	storageDir := b.paths.PodmanStorage
	env := os.Environ()
	env = append(env,
		"CONTAINERS_STORAGE_CONF="+storageCfg,
		"TMPDIR="+filepath.Join(storageDir, "tmp"),
	)

	return b.runEnv(env, "podman", args...)
}

// PodmanPush pushes the built image using the same isolated storage.
func (b *CloudBuilder) PodmanPush(tag string) error {
	ui.Info("Pushing: %s", tag)
	storageCfg := filepath.Join(b.paths.BuildDir, "storage.conf")
	env := append(os.Environ(), "CONTAINERS_STORAGE_CONF="+storageCfg)
	return b.runEnv(env, "podman", "push", tag)
}

// CosignSign signs the pushed image with cosign keyless signing.
func (b *CloudBuilder) CosignSign(tag string) error {
	ui.Info("Signing with cosign: %s", tag)
	return b.runEnv(os.Environ(), "cosign", "sign", "--yes", tag)
}

func (b *CloudBuilder) run(name string, args ...string) error {
	return b.runEnv(os.Environ(), name, args...)
}

func (b *CloudBuilder) runEnv(env []string, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Env = env
	cmd.Stderr = os.Stderr
	if b.verbose {
		cmd.Stdout = os.Stdout
	}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	ui.OK("%s done", name)
	return nil
}

func hasDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

// RunPreScripts executes scripts/pre/ on the HOST before any build step.
// These run with full host access — useful for checking dependencies,
// pre-pulling images, validating environment, setting up secrets etc.
// Order: alphabetical. Supported: .sh .py .pl .rb
func (b *CloudBuilder) RunPreScripts() error {
	if !hasDir(b.paths.ScriptsPre) {
		ui.Info("No scripts/pre/ directory — skipping")
		return nil
	}
	entries, err := os.ReadDir(b.paths.ScriptsPre)
	if err != nil {
		return fmt.Errorf("cannot read scripts/pre/: %w", err)
	}
	interps := map[string]string{
		".sh": "bash", ".bash": "bash",
		".py": "python3",
		".pl": "perl",
		".rb": "ruby",
	}
	ran := 0
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		ext := filepath.Ext(e.Name())
		interp, ok := interps[ext]
		if !ok {
			continue
		}
		scriptPath := filepath.Join(b.paths.ScriptsPre, e.Name())
		ui.Info("[pre] %s  (%s)", e.Name(), interp)
		cmd := exec.Command(interp, scriptPath)
		cmd.Env = append(os.Environ(),
			"LEGENDARYOS_PROJECT="+b.cfg.Project.Name,
			"LEGENDARYOS_VERSION="+b.cfg.Project.Version,
			"LEGENDARYOS_BUILD="+b.paths.BuildDir,
			"LEGENDARYOS_ROOT="+b.paths.Root,
		)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("pre-script %s failed: %w", e.Name(), err)
		}
		ran++
	}
	if ran > 0 {
		ui.OK("Pre-scripts done (%d ran)", ran)
	}
	return nil
}
