package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/legendaryos/builder/src/config"
	"github.com/legendaryos/builder/src/ui"
)

// CloudBuilder builds an OCI bootc container image using podman.
//
// Pipeline:
//   1. Validate project
//   2. Prepare build/ dirs
//   3. Copy repos/ into build context
//   4. Generate Containerfile  (from config + install.packages + files/ + scripts/)
//   5. podman build --tag <registry/image:tag>
//   6. (optional) podman push
//   7. (optional) cosign sign
type CloudBuilder struct {
	cfg     *config.Config
	paths   *config.Paths
	verbose bool
	release bool
}

func NewCloud(cfg *config.Config, paths *config.Paths, verbose, release bool) *CloudBuilder {
	return &CloudBuilder{cfg: cfg, paths: paths, verbose: verbose, release: release}
}

func (b *CloudBuilder) Validate() error {
	if b.cfg.Project.BaseDistro != "fedora" {
		return fmt.Errorf("unsupported distro %q — only 'fedora' is supported", b.cfg.Project.BaseDistro)
	}
	if b.cfg.Project.BaseVersion < 44 {
		return fmt.Errorf("Fedora %d is not supported — minimum is Fedora 44", b.cfg.Project.BaseVersion)
	}
	ui.OK("Project valid — Fedora %d / %s", b.cfg.Project.BaseVersion, b.cfg.Project.Arch)
	return nil
}

func (b *CloudBuilder) PrepareDirs() error {
	dirs := []string{
		b.paths.BuildDir,
		b.paths.CacheDir,
		b.paths.OutputDir,
		filepath.Join(b.paths.BuildDir, "context", "repos"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			return fmt.Errorf("cannot create %s: %w", d, err)
		}
	}
	ui.OK("Build directories ready")
	return nil
}

// CopyRepos copies *.repo files from repos/ into the build context so the
// Containerfile can reference them with a COPY instruction.
func (b *CloudBuilder) CopyRepos() error {
	if _, err := os.Stat(b.paths.ReposDir); os.IsNotExist(err) {
		ui.Info("No repos/ directory — using base image defaults")
		return nil
	}
	entries, err := os.ReadDir(b.paths.ReposDir)
	if err != nil {
		return fmt.Errorf("cannot read repos/: %w", err)
	}
	destDir := filepath.Join(b.paths.BuildDir, "context", "repos")
	count := 0
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".repo") {
			data, err := os.ReadFile(filepath.Join(b.paths.ReposDir, e.Name()))
			if err != nil {
				return err
			}
			if err := os.WriteFile(filepath.Join(destDir, e.Name()), data, 0644); err != nil {
				return err
			}
			ui.Info("Repo: %s", e.Name())
			count++
		}
	}
	ui.OK("Copied %d repo file(s) into build context", count)
	return nil
}

// GenerateContainerfile renders the Containerfile and writes it to build/Containerfile.
func (b *CloudBuilder) GenerateContainerfile(platform string) error {
	installPkgs, err := config.ReadPackageList(b.paths.InstallPkgs)
	if err != nil {
		return fmt.Errorf("cannot read install.packages: %w", err)
	}
	removePkgs, err := config.ReadPackageList(b.paths.RemovePkgs)
	if err != nil {
		return fmt.Errorf("cannot read remove.packages: %w", err)
	}

	cf := b.renderContainerfile(installPkgs, removePkgs, platform)

	cfPath := filepath.Join(b.paths.BuildDir, "Containerfile")
	if err := os.WriteFile(cfPath, []byte(cf), 0644); err != nil {
		return fmt.Errorf("cannot write Containerfile: %w", err)
	}
	ui.OK("Containerfile → %s", cfPath)

	if b.verbose {
		ui.Divider()
		fmt.Fprint(ui.Out, cf)
		ui.Divider()
	}
	if len(installPkgs) > 0 {
		ui.PackageListDisplay("Will install", installPkgs)
	}
	if len(removePkgs) > 0 {
		ui.PackageListDisplay("Will remove", removePkgs)
	}
	return nil
}

func (b *CloudBuilder) renderContainerfile(install, remove []string, platform string) string {
	cfg := b.cfg
	base := fmt.Sprintf("quay.io/fedora/fedora-bootc:%d", cfg.Project.BaseVersion)

	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}
	comment := func(s string) { line("# " + s) }
	blank := func() { line("") }

	comment("╔══════════════════════════════════════════════════════════════╗")
	comment("║  Generated by LegendaryOS Builder — DO NOT EDIT MANUALLY   ║")
	comment("║  Regenerate with: legendaryos build cloud                   ║")
	comment("╚══════════════════════════════════════════════════════════════╝")
	blank()

	// FROM
	line("FROM --platform=%s %s", platform, base)
	blank()

	// Labels
	comment("── Labels ───────────────────────────────────────────────────────")
	line("LABEL org.opencontainers.image.title=%q", cfg.Project.Name)
	line("LABEL org.opencontainers.image.version=%q", cfg.Project.Version)
	line("LABEL org.opencontainers.image.description=%q", cfg.Project.Description)
	line("LABEL org.opencontainers.image.licenses=%q", cfg.Project.License)
	line("LABEL com.legendaryos.builder.version=\"1.0.0\"")
	blank()

	// Custom repos
	if hasDir(b.paths.ReposDir) {
		comment("── Custom repositories ────────────────────────────────────────────")
		comment("  Copied from repos/ by legendaryos into build/context/repos/")
		line("COPY build/context/repos/ /etc/yum.repos.d/")
		blank()
	}

	// Local RPMs from packages/
	if hasDir(b.paths.PackagesDir) {
		comment("── Local RPM packages (packages/) ─────────────────────────────────")
		line("COPY packages/ /tmp/los-rpms/")
		line("RUN dnf install -y /tmp/los-rpms/*.rpm 2>/dev/null || true \\")
		line("    && rm -rf /tmp/los-rpms")
		blank()
	}

	// files/before/ overlay
	if hasDir(b.paths.FilesBefore) {
		comment("── Pre-install overlay (files/before/) ────────────────────────────")
		line("COPY files/before/ /")
		blank()
	}

	// Install packages
	if len(install) > 0 {
		comment("── Install packages (install.packages) ────────────────────────────")
		line("RUN dnf install -y \\")
		for _, pkg := range install {
			line("    %s \\", pkg)
		}
		line("    && dnf clean all \\")
		line("    && rm -rf /var/cache/dnf")
		blank()
	}

	// Remove packages
	if len(remove) > 0 {
		comment("── Remove packages (remove.packages) ──────────────────────────────")
		line("RUN dnf remove -y \\")
		for i, pkg := range remove {
			if i < len(remove)-1 {
				line("    %s \\", pkg)
			} else {
				line("    %s", pkg)
			}
		}
		blank()
	}

	// files/after/ overlay
	if hasDir(b.paths.FilesAfter) {
		comment("── Post-install overlay (files/after/) ────────────────────────────")
		line("COPY files/after/ /")
		blank()
	}

	// Scripts — all supported interpreters in one RUN
	if hasDir(b.paths.ScriptsDir) {
		comment("── Hooks / scripts (scripts/) ─────────────────────────────────────")
		comment("  .sh → bash   .py → python3   .pl → perl   .rb → ruby")
		line("COPY scripts/ /tmp/los-scripts/")
		line("RUN set -eux \\")
		line("    && for f in $(ls /tmp/los-scripts/*.sh  2>/dev/null | sort); do bash    \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts/*.py  2>/dev/null | sort); do python3 \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts/*.pl  2>/dev/null | sort); do perl    \"$f\"; done \\")
		line("    && for f in $(ls /tmp/los-scripts/*.rb  2>/dev/null | sort); do ruby    \"$f\"; done \\")
		line("    && rm -rf /tmp/los-scripts")
		blank()
	}

	// System configuration
	comment("── System configuration ────────────────────────────────────────────")
	if cfg.System.Hostname != "" {
		line("RUN echo %q > /etc/hostname", cfg.System.Hostname)
	}
	if cfg.System.Locale != "" {
		line("RUN echo 'LANG=%s' > /etc/locale.conf", cfg.System.Locale)
	}
	if cfg.System.Keyboard != "" {
		line("RUN echo 'KEYMAP=%s' > /etc/vconsole.conf", cfg.System.Keyboard)
	}
	if cfg.System.Timezone != "" {
		line("RUN ln -sf /usr/share/zoneinfo/%s /etc/localtime || true", cfg.System.Timezone)
	}
	if cfg.System.SELinux != "" {
		line("RUN sed -i 's/^SELINUX=.*/SELINUX=%s/' /etc/selinux/config 2>/dev/null || true", cfg.System.SELinux)
	}
	for _, svc := range cfg.System.Services {
		line("RUN systemctl enable  %s 2>/dev/null || true", svc)
	}
	for _, svc := range cfg.System.Disable {
		line("RUN systemctl disable %s 2>/dev/null || true", svc)
	}
	if cfg.System.Firewall {
		line("RUN systemctl enable firewalld.service 2>/dev/null || true")
	}
	blank()

	// Release mode
	if b.release {
		comment("── Release: strip debug symbols ────────────────────────────────────")
		line("RUN dnf remove -y gdb-minimal 2>/dev/null || true \\")
		line("    && find /usr/lib/debug -type f -delete 2>/dev/null || true \\")
		line("    && find /usr/src/debug -type f -delete 2>/dev/null || true")
		blank()
	}

	// bootc commit — MUST be last
	comment("── bootc: commit ostree layer — MUST be the last RUN ───────────────")
	line("RUN ostree container commit")

	return sb.String()
}

// PodmanBuild runs `podman build` to produce the tagged image.
//
// What podman does internally:
//   - Reads the Containerfile layer by layer
//   - Each RUN spins up a temporary container, executes the command,
//     captures the filesystem diff as a new layer
//   - Final image = stacked layers stored in local podman image store
func (b *CloudBuilder) PodmanBuild(tag string, noCache bool) error {
	cfPath := filepath.Join(b.paths.BuildDir, "Containerfile")

	// Build context = project root so COPY files/after/ etc. resolve correctly
	args := []string{"build", "--tag", tag, "--file", cfPath}
	if noCache {
		args = append(args, "--no-cache")
	}
	if b.release {
		// squash-all merges all layers into one → smaller image
		args = append(args, "--squash-all")
	}
	args = append(args, b.paths.Root)

	ui.Info("podman %s", strings.Join(args, " "))
	return b.run("podman", args...)
}

// PodmanPush pushes the built image to the OCI registry.
// The registry URL comes from the image tag (e.g. ghcr.io/org/name:tag).
func (b *CloudBuilder) PodmanPush(tag string) error {
	ui.Info("Pushing: %s", tag)
	return b.run("podman", "push", tag)
}

// CosignSign signs the pushed image in-registry using cosign keyless signing.
// Requires OIDC token (available in GitHub Actions via id-token permission).
func (b *CloudBuilder) CosignSign(tag string) error {
	ui.Info("Signing with cosign: %s", tag)
	return b.run("cosign", "sign", "--yes", tag)
}

func (b *CloudBuilder) run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Env = os.Environ()
	if b.verbose {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
	} else {
		// capture stderr so we can show it on failure
		cmd.Stderr = os.Stderr
	}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	ui.OK("%s done", name)
	return nil
}

func hasDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}
