package builder

import (
	"fmt"
	"strings"

	"github.com/legendaryos/builder/src/config"
)

// generateKickstart produces a full Anaconda kickstart from project config.
// Flatpak installs/removals are executed in %post since they operate on the
// live installed system, not inside the container image.
func generateKickstart(cfg *config.Config, paths *config.Paths) (string, error) {
	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}
	blank   := func() { line("") }
	comment := func(s string) { line("# " + s) }

	comment("╔══════════════════════════════════════════════════════════════╗")
	comment("║  Anaconda Kickstart — Generated by LegendaryOS Builder       ║")
	comment("║  Do not edit manually                                         ║")
	comment("╚══════════════════════════════════════════════════════════════╝")
	blank()

	// ── Installation mode ─────────────────────────────────────────────────
	if cfg.Anaconda.WebUI {
		line("graphical")
	} else {
		line("text")
	}
	blank()

	// ── Locale / keyboard / timezone ──────────────────────────────────────
	line("lang %s", orDefault(cfg.Anaconda.DefaultLang, "en_US.UTF-8"))
	line("keyboard --vckeymap=%s --xlayouts='%s'",
		orDefault(cfg.Anaconda.DefaultKeyboard, "us"),
		orDefault(cfg.Anaconda.DefaultKeyboard, "us"))
	line("timezone %s --utc", orDefault(cfg.Anaconda.DefaultTimezone, "UTC"))
	blank()

	// ── Network ───────────────────────────────────────────────────────────
	line("network --bootproto=dhcp --hostname=%s",
		orDefault(cfg.System.Hostname, "legendaryos"))
	blank()

	// ── Bootloader ────────────────────────────────────────────────────────
	kernelArgs := orDefault(cfg.Boot.KernelArgs, "quiet splash")
	// Append [bootloader] extra_args when section is active
	if cfg.Bootloader.Enabled && cfg.Bootloader.ExtraArgs != "" {
		if !strings.Contains(kernelArgs, cfg.Bootloader.ExtraArgs) {
			kernelArgs += " " + cfg.Bootloader.ExtraArgs
		}
	}
	// If NVIDIA KMS is enabled, add the required kernel parameters
	if cfg.Nvidia.Enabled && cfg.Nvidia.EnableKMS {
		if !strings.Contains(kernelArgs, "nvidia-drm.modeset") {
			kernelArgs += " nvidia-drm.modeset=1 nvidia-drm.fbdev=1"
		}
	}

	// Select kickstart bootloader directive based on resolved bootloader type
	resolvedBL := cfg.ResolvedBootloader()
	switch strings.ToLower(resolvedBL) {
	case config.BootloaderSystemd:
		line("bootloader --location=none --boot-drive=sda")
		comment("  systemd-boot: bootctl will be used in %post")
	case config.BootloaderRefind:
		line("bootloader --location=none --boot-drive=sda")
		comment("  rEFInd: refind-install will be used in %post")
	default:
		line("bootloader --location=mbr --append=%q", kernelArgs)
	}
	blank()

	// ── Disk partitioning ─────────────────────────────────────────────────
	line("zerombr")
	line("clearpart --all --initlabel")
	switch strings.ToLower(resolvedBL) {
	case config.BootloaderSystemd, config.BootloaderRefind:
		line("part /boot/efi --fstype=efi  --size=512")
		line("part /boot     --fstype=ext4 --size=1024")
		line("part pv.01     --grow")
		line("volgroup vg_root pv.01")
		line("logvol /  --vgname=vg_root --size=1 --grow --fstype=%s --name=lv_root", cfg.Build.Filesystem)
	default:
		line("autopart --type=lvm")
	}
	blank()

	// ── Security ──────────────────────────────────────────────────────────
	line("selinux --%s", orDefault(cfg.System.SELinux, "enforcing"))
	if cfg.System.Firewall {
		line("firewall --enabled --service=ssh")
	} else {
		line("firewall --disabled")
	}
	blank()

	// ── Root & users ──────────────────────────────────────────────────────
	if cfg.Anaconda.RootPasswordLock {
		line("rootpw --lock")
	}
	if cfg.Anaconda.UserName != "" {
		groups := ""
		if len(cfg.Anaconda.UserGroups) > 0 {
			groups = " --groups=" + strings.Join(cfg.Anaconda.UserGroups, ",")
		}
		line("user --name=%s%s", cfg.Anaconda.UserName, groups)
	}
	blank()

	// ── Additional repos needed at install time ───────────────────────────
	if cfg.Nvidia.Enabled {
		comment("── RPM Fusion repos (required for NVIDIA drivers) ───────────────")
		line("repo --name=rpmfusion-free --baseurl=https://download1.rpmfusion.org/free/fedora/releases/%d/Everything/x86_64/os/", cfg.Project.BaseVersion)
		line("repo --name=rpmfusion-nonfree --baseurl=https://download1.rpmfusion.org/nonfree/fedora/releases/%d/Everything/x86_64/os/", cfg.Project.BaseVersion)
		blank()
	}

	// ── %packages ─────────────────────────────────────────────────────────
	if cfg.Nvidia.Enabled || cfg.Bootloader.Enabled {
		comment("── Packages installed by Anaconda ───────────────────────────────")
		line("%packages")
		if cfg.Nvidia.Enabled {
			comment("NVIDIA proprietary driver via akmod")
			line("akmod-nvidia")
			line("xorg-x11-drv-nvidia")
			line("xorg-x11-drv-nvidia-libs")
			line("xorg-x11-drv-nvidia-libs.i686")
			if cfg.Nvidia.OpenDriver {
				line("akmod-nvidia-open")
			}
			if cfg.Nvidia.InstallCUDA {
				line("xorg-x11-drv-nvidia-cuda")
				line("xorg-x11-drv-nvidia-cuda-libs")
			}
			if cfg.Nvidia.InstallNVIDIASettings {
				line("nvidia-settings")
			}
			if cfg.Nvidia.InstallVAAPI {
				line("nvidia-vaapi-driver")
			}
			if cfg.Nvidia.InstallVulkan {
				line("vulkan-loader")
				line("vulkan-headers")
			}
			line("xorg-x11-drv-nvidia-power")
		}
		if cfg.Bootloader.Enabled {
			switch strings.ToLower(cfg.Bootloader.Type) {
			case config.BootloaderRefind:
				line("refind")
			case config.BootloaderLimine:
				line("limine")
			case config.BootloaderSystemd:
				line("systemd-boot-unsigned")
				line("efi-filesystem")
			case config.BootloaderSyslinux:
				line("syslinux")
				line("syslinux-extlinux")
			}
			for _, pkg := range cfg.Bootloader.InstallPackages {
				line("%s", pkg)
			}
		}
		line("%end")
		blank()
	}

	// ── %post ─────────────────────────────────────────────────────────────
	line("%post")
	comment("── OS identity ──────────────────────────────────────────────────")
	line("echo '# Installed by LegendaryOS Builder' >> /etc/os-release")
	if cfg.Project.Name != "" {
		line("echo 'VARIANT=%q' >> /etc/os-release", cfg.Project.Name)
		line("echo 'VARIANT_ID=%q' >> /etc/os-release",
			strings.ToLower(strings.ReplaceAll(cfg.Project.Name, " ", "-")))
	}
	if cfg.Project.IsClassic() {
		line("echo 'VARIANT_PLATFORM=classic' >> /etc/os-release")
	}
	blank()

	if cfg.Nvidia.Enabled {
		sb.WriteString(nvidiaPostScript(cfg))
	}

	if cfg.Bootloader.Enabled {
		sb.WriteString(bootloaderPostScript(cfg))
	}

	// Flatpak — applied at install time via %post, NOT during container build
	var flatpakInstall, flatpakRemove []string
	if paths != nil {
		flatpakInstall, _ = config.ReadPackageList(paths.FlatpakPkgs)
		flatpakRemove, _  = config.ReadPackageList(paths.FlatpakRemovePkgs)
	}
	if len(flatpakInstall) > 0 || len(flatpakRemove) > 0 {
		sb.WriteString(flatpakPostScript(flatpakInstall, flatpakRemove))
	}

	line("%end")
	blank()
	line("reboot")

	return sb.String(), nil
}

// nvidiaPostScript returns the %post shell commands for NVIDIA setup.
// This runs inside the installed system (chroot) after package installation.
func nvidiaPostScript(cfg *config.Config) string {
	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}
	comment := func(s string) { line("# " + s) }
	blank   := func()         { line("") }

	comment("╔══════════════════════════════════════════════════════════════╗")
	comment("║  NVIDIA proprietary driver setup                             ║")
	comment("╚══════════════════════════════════════════════════════════════╝")
	blank()

	if cfg.Nvidia.BlacklistNouveau {
		comment("── Blacklist nouveau ────────────────────────────────────────────")
		line("cat > /etc/modprobe.d/blacklist-nouveau.conf << 'EOF'")
		line("# Blacklisted by LegendaryOS Builder — NVIDIA proprietary driver in use")
		line("blacklist nouveau")
		line("blacklist lbm-nouveau")
		line("options nouveau modeset=0")
		line("alias nouveau off")
		line("alias lbm-nouveau off")
		line("EOF")
		blank()
		comment("Regenerate initramfs so nouveau is excluded from early boot")
		line("dracut --force --omit-drivers nouveau 2>/dev/null || true")
		blank()
	}

	if cfg.Nvidia.EnableKMS {
		comment("── NVIDIA KMS — required for Wayland support ────────────────────")
		line("cat > /etc/modprobe.d/nvidia-kms.conf << 'EOF'")
		line("# NVIDIA KMS — enabled by LegendaryOS Builder")
		line("options nvidia-drm modeset=1 fbdev=1")
		line("EOF")
		blank()
	}

	comment("── nvidia-modprobe — allow non-root apps to use GPU ─────────────")
	line("cat > /etc/modprobe.d/nvidia.conf << 'EOF'")
	line("# NVIDIA options — LegendaryOS Builder")
	line("options nvidia NVreg_PreserveVideoMemoryAllocations=1")
	line("options nvidia NVreg_TemporaryFilePath=/tmp")
	line("EOF")
	blank()

	comment("── NVIDIA power management ───────────────────────────────────────")
	line("systemctl enable nvidia-suspend.service  2>/dev/null || true")
	line("systemctl enable nvidia-hibernate.service 2>/dev/null || true")
	line("systemctl enable nvidia-resume.service   2>/dev/null || true")
	blank()

	comment("── akmods — compile NVIDIA kernel module on first boot ───────────")
	line("systemctl enable akmods.service 2>/dev/null || true")
	blank()

	if cfg.Nvidia.InstallVAAPI {
		comment("── NVIDIA VAAPI driver ───────────────────────────────────────────")
		line("cat >> /etc/environment << 'EOF'")
		line("# NVIDIA VAAPI — LegendaryOS")
		line("LIBVA_DRIVER_NAME=nvidia")
		line("EOF")
		blank()
	}

	comment("── Wayland + NVIDIA environment ──────────────────────────────────")
	line("cat >> /etc/environment << 'EOF'")
	line("# NVIDIA Wayland — LegendaryOS")
	line("GBM_BACKEND=nvidia-drm")
	line("__GLX_VENDOR_LIBRARY_NAME=nvidia")
	line("WLR_NO_HARDWARE_CURSORS=1")
	line("ELECTRON_OZONE_PLATFORM_HINT=wayland")
	line("EOF")
	blank()

	comment("── udev — NVIDIA device permissions ─────────────────────────────")
	line("cat > /etc/udev/rules.d/70-nvidia.rules << 'EOF'")
	line("# NVIDIA device permissions — LegendaryOS Builder")
	line("KERNEL==\"nvidia\",          RUN+=\"/usr/bin/nvidia-modprobe -c0 -u\"")
	line("KERNEL==\"nvidia_modeset\",  SUBSYSTEM==\"module\", ACTION==\"add\", DEVPATH==\"/module/nvidia_modeset\", RUN+=\"/usr/bin/nvidia-modprobe -c0 -u\"")
	line("KERNEL==\"nvidia_uvm\",      RUN+=\"/usr/bin/nvidia-modprobe -m\"")
	line("KERNEL==\"nvidia_drm\",      RUN+=\"/usr/bin/nvidia-modprobe -m\"")
	line("KERNEL==\"nvidiactl\",       GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia[0-9]*\",    GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia-modeset\",  GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia-uvm\",      GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia-uvm-tools\",GROUP=\"video\", MODE=\"0660\"")
	line("EOF")
	blank()

	comment("── Regenerate initramfs with NVIDIA modules ──────────────────────")
	line("dracut --force 2>/dev/null || true")
	blank()

	comment("── GPU detection info (written to /etc/legendaryos-nvidia.conf) ──")
	line("GPU_INFO=$(lspci -nn | grep -i 'vga\\|3d\\|display' | grep -i nvidia || echo 'NVIDIA GPU not detected at install time')")
	line("cat > /etc/legendaryos-nvidia.conf << EOF")
	line("# LegendaryOS NVIDIA driver configuration")
	line("# Generated at install time: $(date)")
	line("#")
	line("# Detected GPU: $GPU_INFO")
	line("#")
	line("# Driver package : akmod-nvidia (proprietary)")
	line("# Kernel module  : nvidia (compiled by akmods on first boot)")
	line("# KMS            : enabled (nvidia-drm.modeset=1)")
	line("# Wayland        : supported")
	if cfg.Nvidia.InstallVAAPI {
		line("# VAAPI          : enabled (LIBVA_DRIVER_NAME=nvidia)")
	}
	if cfg.Nvidia.InstallCUDA {
		line("# CUDA           : installed")
	}
	line("EOF")
	blank()

	comment("── NVIDIA setup complete ─────────────────────────────────────────")
	comment("  First boot will compile the kernel module (~2-3 min).")
	comment("  After reboot: nvidia-smi should show your GPU.")

	return sb.String()
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
