package builder

import (
	"fmt"
	"strings"

	"github.com/legendaryos/builder/src/config"
)

// generateKickstart produces a full Anaconda kickstart from project config.
func generateKickstart(cfg *config.Config) (string, error) {
	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}
	blank  := func() { line("") }
	comment := func(s string) { line("# " + s) }

	comment("╔══════════════════════════════════════════════════════════════╗")
	comment("║  Anaconda Kickstart — Generated by LegendaryOS Builder       ║")
	comment("║  Do not edit manually                                         ║")
	comment("╚══════════════════════════════════════════════════════════════╝")
	blank()

	// ── Installation mode ─────────────────────────────────────────────────
	if cfg.Anaconda.WebUI {
		line("graphical")
	} else {
		line("text")
	}
	blank()

	// ── Locale / keyboard / timezone ──────────────────────────────────────
	line("lang %s", orDefault(cfg.Anaconda.DefaultLang, "en_US.UTF-8"))
	line("keyboard --vckeymap=%s --xlayouts='%s'",
		orDefault(cfg.Anaconda.DefaultKeyboard, "us"),
		orDefault(cfg.Anaconda.DefaultKeyboard, "us"))
	line("timezone %s --utc", orDefault(cfg.Anaconda.DefaultTimezone, "UTC"))
	blank()

	// ── Network ───────────────────────────────────────────────────────────
	line("network --bootproto=dhcp --hostname=%s",
		orDefault(cfg.System.Hostname, "legendaryos"))
	blank()

	// ── Bootloader ────────────────────────────────────────────────────────
	kernelArgs := orDefault(cfg.Boot.KernelArgs, "quiet splash")
	// If NVIDIA KMS is enabled, add the required kernel parameters
	if cfg.Nvidia.Enabled && cfg.Nvidia.EnableKMS {
		if !strings.Contains(kernelArgs, "nvidia-drm.modeset") {
			kernelArgs += " nvidia-drm.modeset=1 nvidia-drm.fbdev=1"
		}
	}
	line("bootloader --location=mbr --append=%q", kernelArgs)
	blank()

	// ── Disk partitioning ─────────────────────────────────────────────────
	line("zerombr")
	line("clearpart --all --initlabel")
	line("autopart --type=lvm")
	blank()

	// ── Security ──────────────────────────────────────────────────────────
	line("selinux --%s", orDefault(cfg.System.SELinux, "enforcing"))
	if cfg.System.Firewall {
		line("firewall --enabled --service=ssh")
	} else {
		line("firewall --disabled")
	}
	blank()

	// ── Root & users ──────────────────────────────────────────────────────
	if cfg.Anaconda.RootPasswordLock {
		line("rootpw --lock")
	}
	if cfg.Anaconda.UserName != "" {
		groups := ""
		if len(cfg.Anaconda.UserGroups) > 0 {
			groups = " --groups=" + strings.Join(cfg.Anaconda.UserGroups, ",")
		}
		line("user --name=%s%s", cfg.Anaconda.UserName, groups)
	}
	blank()

	// ── Additional repos needed at install time ───────────────────────────
	// RPM Fusion is needed for NVIDIA drivers
	if cfg.Nvidia.Enabled {
		comment("── RPM Fusion repos (required for NVIDIA drivers) ───────────────")
		line("repo --name=rpmfusion-free --baseurl=https://download1.rpmfusion.org/free/fedora/releases/%d/Everything/x86_64/os/", cfg.Project.BaseVersion)
		line("repo --name=rpmfusion-nonfree --baseurl=https://download1.rpmfusion.org/nonfree/fedora/releases/%d/Everything/x86_64/os/", cfg.Project.BaseVersion)
		blank()
	}

	// ── %packages ─────────────────────────────────────────────────────────
	if cfg.Nvidia.Enabled {
		comment("── Packages installed by Anaconda ───────────────────────────────")
		line("%%packages")
		comment("NVIDIA proprietary driver via akmod (compiles module on first boot)")
		comment("akmod-nvidia supports ALL NVIDIA GPUs from Kepler (GTX 600) onward")
		line("akmod-nvidia")
		line("xorg-x11-drv-nvidia")
		line("xorg-x11-drv-nvidia-libs")
		line("xorg-x11-drv-nvidia-libs.i686")   // 32-bit libs for Steam/Wine
		if cfg.Nvidia.OpenDriver {
			comment("nvidia-open: open-source kernel module (Turing+ / RTX 20xx+)")
			line("akmod-nvidia-open")
		}
		if cfg.Nvidia.InstallCUDA {
			comment("CUDA toolkit — large download, needed for ML/AI/compute workloads")
			line("xorg-x11-drv-nvidia-cuda")
			line("xorg-x11-drv-nvidia-cuda-libs")
		}
		if cfg.Nvidia.InstallNVIDIASettings {
			line("nvidia-settings")
		}
		if cfg.Nvidia.InstallVAAPI {
			comment("VAAPI driver — hardware-accelerated video decode (Firefox, MPV, etc.)")
			line("nvidia-vaapi-driver")
		}
		if cfg.Nvidia.InstallVulkan {
			comment("Vulkan ICD for NVIDIA")
			line("vulkan-loader")
			line("vulkan-headers")
		}
		comment("Power management for NVIDIA (suspend/resume)")
		line("xorg-x11-drv-nvidia-power")
		line("%%end")
		blank()
	}

	// ── %post ─────────────────────────────────────────────────────────────
	line("%%post")
	comment("── OS identity ──────────────────────────────────────────────────")
	line("echo '# Installed by LegendaryOS Builder' >> /etc/os-release")
	if cfg.Project.Name != "" {
		line("echo 'VARIANT=%q' >> /etc/os-release", cfg.Project.Name)
		line("echo 'VARIANT_ID=%q' >> /etc/os-release",
			strings.ToLower(strings.ReplaceAll(cfg.Project.Name, " ", "-")))
	}
	blank()

	if cfg.Nvidia.Enabled {
		sb.WriteString(nvidiaPostScript(cfg))
	}

	line("%%end")
	blank()
	line("reboot")

	return sb.String(), nil
}

// nvidiaPostScript returns the %post shell commands for NVIDIA setup.
// This runs inside the installed system (chroot) after package installation.
func nvidiaPostScript(cfg *config.Config) string {
	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}
	comment := func(s string) { line("# " + s) }
	blank := func() { line("") }

	comment("╔══════════════════════════════════════════════════════════════╗")
	comment("║  NVIDIA proprietary driver setup                             ║")
	comment("╚══════════════════════════════════════════════════════════════╝")
	blank()

	// 1. Blacklist nouveau
	if cfg.Nvidia.BlacklistNouveau {
		comment("── Blacklist nouveau (open-source NVIDIA driver) ────────────────")
		comment("  nouveau must not load alongside the proprietary driver.")
		line("cat > /etc/modprobe.d/blacklist-nouveau.conf << 'EOF'")
		line("# Blacklisted by LegendaryOS Builder — NVIDIA proprietary driver in use")
		line("blacklist nouveau")
		line("blacklist lbm-nouveau")
		line("options nouveau modeset=0")
		line("alias nouveau off")
		line("alias lbm-nouveau off")
		line("EOF")
		blank()
		comment("Regenerate initramfs so nouveau is excluded from early boot")
		line("dracut --force --omit-drivers nouveau 2>/dev/null || true")
		blank()
	}

	// 2. KMS (Kernel Mode Setting) — required for Wayland
	if cfg.Nvidia.EnableKMS {
		comment("── NVIDIA KMS — required for Wayland support ────────────────────")
		comment("  nvidia-drm.modeset=1 enables the DRM kernel mode setting.")
		comment("  nvidia-drm.fbdev=1   enables framebuffer for console (Fedora 40+).")
		line("cat > /etc/modprobe.d/nvidia-kms.conf << 'EOF'")
		line("# NVIDIA KMS — enabled by LegendaryOS Builder")
		line("options nvidia-drm modeset=1 fbdev=1")
		line("EOF")
		blank()
	}

	// 3. nvidia-modprobe config
	comment("── nvidia-modprobe — allow non-root apps to use GPU ─────────────")
	line("cat > /etc/modprobe.d/nvidia.conf << 'EOF'")
	line("# NVIDIA options — LegendaryOS Builder")
	line("options nvidia NVreg_PreserveVideoMemoryAllocations=1")
	line("options nvidia NVreg_TemporaryFilePath=/tmp")
	line("EOF")
	blank()

	// 4. NVIDIA power management (needed for proper suspend/resume)
	comment("── NVIDIA power management ───────────────────────────────────────")
	comment("  Enables suspend/resume support — important for laptops.")
	line("systemctl enable nvidia-suspend.service  2>/dev/null || true")
	line("systemctl enable nvidia-hibernate.service 2>/dev/null || true")
	line("systemctl enable nvidia-resume.service   2>/dev/null || true")
	blank()

	// 5. akmods — wait for module compilation on first boot
	comment("── akmods — compile NVIDIA kernel module on first boot ───────────")
	comment("  akmod-nvidia compiles the driver for the installed kernel.")
	comment("  This runs automatically on first boot — takes 1-3 minutes.")
	comment("  The system may appear to hang during first boot — this is normal.")
	line("systemctl enable akmods.service 2>/dev/null || true")
	blank()

	// 6. VAAPI
	if cfg.Nvidia.InstallVAAPI {
		comment("── NVIDIA VAAPI driver ───────────────────────────────────────────")
		comment("  Enables hardware-accelerated video decode in:")
		comment("  Firefox, Chromium, MPV, VLC, GStreamer pipelines.")
		line("cat >> /etc/environment << 'EOF'")
		line("# NVIDIA VAAPI — LegendaryOS")
		line("LIBVA_DRIVER_NAME=nvidia")
		line("EOF")
		blank()
	}

	// 7. Wayland environment
	comment("── Wayland + NVIDIA environment ──────────────────────────────────")
	comment("  These env vars ensure Wayland apps use the NVIDIA GPU.")
	line("cat >> /etc/environment << 'EOF'")
	line("# NVIDIA Wayland — LegendaryOS")
	line("GBM_BACKEND=nvidia-drm")
	line("__GLX_VENDOR_LIBRARY_NAME=nvidia")
	line("WLR_NO_HARDWARE_CURSORS=1")
	line("ELECTRON_OZONE_PLATFORM_HINT=wayland")
	line("EOF")
	blank()

	// 8. udev rule — allow users in 'video' group to access NVIDIA devices
	comment("── udev — NVIDIA device permissions ─────────────────────────────")
	line("cat > /etc/udev/rules.d/70-nvidia.rules << 'EOF'")
	line("# NVIDIA device permissions — LegendaryOS Builder")
	line("KERNEL==\"nvidia\",          RUN+=\"/usr/bin/nvidia-modprobe -c0 -u\"")
	line("KERNEL==\"nvidia_modeset\",  SUBSYSTEM==\"module\", ACTION==\"add\", DEVPATH==\"/module/nvidia_modeset\", RUN+=\"/usr/bin/nvidia-modprobe -c0 -u\"")
	line("KERNEL==\"nvidia_uvm\",      RUN+=\"/usr/bin/nvidia-modprobe -m\"")
	line("KERNEL==\"nvidia_drm\",      RUN+=\"/usr/bin/nvidia-modprobe -m\"")
	line("KERNEL==\"nvidiactl\",       GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia[0-9]*\",    GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia-modeset\",  GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia-uvm\",      GROUP=\"video\", MODE=\"0660\"")
	line("KERNEL==\"nvidia-uvm-tools\",GROUP=\"video\", MODE=\"0660\"")
	line("EOF")
	blank()

	// 9. Regenerate initramfs with NVIDIA modules included
	comment("── Regenerate initramfs with NVIDIA modules ──────────────────────")
	comment("  This ensures NVIDIA is available at early boot.")
	line("dracut --force 2>/dev/null || true")
	blank()

	// 10. Detection info for user
	comment("── GPU detection info (written to /etc/legendaryos-nvidia.conf) ──")
	line("GPU_INFO=$(lspci -nn | grep -i 'vga\\|3d\\|display' | grep -i nvidia || echo 'NVIDIA GPU not detected at install time')")
	line("cat > /etc/legendaryos-nvidia.conf << EOF")
	line("# LegendaryOS NVIDIA driver configuration")
	line("# Generated at install time: $(date)")
	line("#")
	line("# Detected GPU: $GPU_INFO")
	line("#")
	line("# Driver package : akmod-nvidia (proprietary)")
	line("# Kernel module  : nvidia (compiled by akmods on first boot)")
	line("# KMS            : enabled (nvidia-drm.modeset=1)")
	line("# Wayland        : supported")
	if cfg.Nvidia.InstallVAAPI {
	line("# VAAPI          : enabled (LIBVA_DRIVER_NAME=nvidia)")
	}
	if cfg.Nvidia.InstallCUDA {
	line("# CUDA           : installed")
	}
	line("EOF")
	blank()

	comment("── NVIDIA setup complete ─────────────────────────────────────────")
	comment("  First boot will compile the kernel module (~2-3 min).")
	comment("  After reboot: nvidia-smi should show your GPU.")
	comment("  Wayland session: KDE Plasma will use NVIDIA via KMS.")

	return sb.String()
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
