package builder

import (
	"fmt"
	"strings"

	"github.com/legendaryos/builder/src/config"
)

// generateKickstart produces an Anaconda kickstart file from the project config.
// Used when [anaconda] enabled = true and the user runs `build iso`.
func generateKickstart(cfg *config.Config) (string, error) {
	var sb strings.Builder
	line := func(s string, a ...interface{}) {
		if len(a) > 0 {
			fmt.Fprintf(&sb, s+"\n", a...)
		} else {
			sb.WriteString(s + "\n")
		}
	}

	line("# Anaconda Kickstart — Generated by LegendaryOS Builder")
	line("# Do not edit — regenerate with: legendaryos build iso")
	line("")

	if cfg.Anaconda.WebUI {
		line("graphical")
	} else {
		line("text")
	}
	line("")

	line("lang %s", orDefault(cfg.Anaconda.DefaultLang, "en_US.UTF-8"))
	line("keyboard --vckeymap=%s --xlayouts='%s'",
		orDefault(cfg.Anaconda.DefaultKeyboard, "us"),
		orDefault(cfg.Anaconda.DefaultKeyboard, "us"))
	line("timezone %s --utc", orDefault(cfg.Anaconda.DefaultTimezone, "UTC"))
	line("")

	line("network --bootproto=dhcp --hostname=%s", orDefault(cfg.System.Hostname, "legendaryos"))
	line("")

	line("bootloader --location=mbr --append=%q", orDefault(cfg.Boot.KernelArgs, "quiet splash"))
	line("")

	line("zerombr")
	line("clearpart --all --initlabel")
	line("autopart --type=lvm")
	line("")

	line("selinux --%s", orDefault(cfg.System.SELinux, "enforcing"))
	if cfg.System.Firewall {
		line("firewall --enabled --service=ssh")
	} else {
		line("firewall --disabled")
	}
	line("")

	if cfg.Anaconda.RootPasswordLock {
		line("rootpw --lock")
	}
	if cfg.Anaconda.UserName != "" {
		groups := ""
		if len(cfg.Anaconda.UserGroups) > 0 {
			groups = " --groups=" + strings.Join(cfg.Anaconda.UserGroups, ",")
		}
		line("user --name=%s%s", cfg.Anaconda.UserName, groups)
	}
	line("")

	line("%%post")
	line("echo '# Installed by LegendaryOS Builder' >> /etc/os-release")
	if cfg.Project.Name != "" {
		line("echo 'VARIANT=%q' >> /etc/os-release", cfg.Project.Name)
		line("echo 'VARIANT_ID=%q' >> /etc/os-release",
			strings.ToLower(strings.ReplaceAll(cfg.Project.Name, " ", "-")))
	}
	line("%%end")
	line("")
	line("reboot")

	return sb.String(), nil
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
